target :PopularMovies do

  pod 'AFNetworking', '~> 3.0'
  pod 'MBProgressHUD', '~> 1.0'
  pod 'Reachability', '~> 3.2'

  target :PopularMoviesTests do
    inherit! :search_paths

    pod 'Specta', '~> 1.0'
    pod 'Expecta', '~> 1.0'
  end
end
